//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kheirieh.datalayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class app_kheiriehEntities : DbContext
    {
        public app_kheiriehEntities()
            : base("name=app_kheiriehEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<marhoom> marhooms { get; set; }
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<taj> tajs { get; set; }
        public virtual DbSet<kerayeh> kerayehs { get; set; }
        public virtual DbSet<kheiriehinfo> kheiriehinfoes { get; set; }
        public virtual DbSet<setingapp> setingapps { get; set; }
        public virtual DbSet<template> templates { get; set; }
    }
}
